### ISSUE TITLE
Forced dependency on StyleCop

### ISSUE THREAD

**Issue by ApocDev** [cloudtoid/url-pattern#1]
Is there a reason why StyleCop is being forced as a dependency when using this library?

I don't think a library aimed at helping match URL patterns should have any say into code style of the project referencing it.

This also causes massive build/intellisense slow-downs on larger projects.

**Comment by prezaei** [comment]
Fix is checked in.

**Comment by prezaei** [comment]
@ApocDev , works for you now?
